### ISSUE TITLE
jinja not work

### ISSUE THREAD

**Issue by Redrex85** [Home-Assistant-Pro-Team/Smart-Laundry-System---Lavatrice#8]
Ciao, prima di tutto complimenti per il lavoro, ho installato tutti i tuoi file, però ho qualche problemino:

![Screenshot 2024-08-03 203430](https://github.com/user-attachments/assets/edecda62-e5e4-4ef3-a22c-9d819d5809ff)

la lavatrice dice attiva da 18 ore anche se ho resettato i sensori, anche se il lavaggio di test è stato di 5 minuti

poi quando apro le statistiche jinja il popup è vuoto, ho tutti gli hacs installati, gli alti menu funzionano tutti bene

mi potete dire come configurare la cartella custom_templates  basta copiarla o bisogna fare altro?

**Comment by Redrex85** [comment]
Registratore: homeassistant.helpers.event
Fonte: helpers/template.py:606
Prima occorrenza: 20:17:33 (30 occorrenze)
Ultima registrazione: 20:35:47

Error while processing template: Template<template=({% from 'history_stats_custom.jinja' import last_use, history %} Generale - {% set fine = state_attr('sensor.lavaggio_terminato','time') | timestamp_custom('%d/%m/%Y alle %H:%M') %} {% if is_state('input_boolean.check_ritirare_panni', 'on') %} {{ '### Panni da ritirare dal ' + fine }} {%elif is_state('binary_sensor.lavatrice', 'on') %} {{ '### Lavatrice in funzione' }} {%else%} {{ 'Ultimo lavaggio terminato il ' + fine }} {% endif %} | Periodo | Costo (â‚¬) | Consumo (KWh) | Tempo | Cicli |:--------|:----------:|:-------------:|:-----:|:--: | <b>Ultimo|{{ ((states[state_attr('sensor.energy_day_lavatrice', 'source')].state | float(0) - state_attr('sensor.lavaggio_iniziato','consumo_iniziale')|float(0)) * (states('input_number.costo_energia_casa') | float(0))) | round(2, default=0)}} â‚¬ | {{ (states[state_attr('sensor.energy_day_lavatrice', 'source')].state | float(0) - state_attr('sensor.lavaggio_iniziato', 'consumo_iniziale') |float(0)) | round(2)}} kWh | {{last_use('sensor.lavaggio_iniziato','sensor.lavaggio_terminato','binary_sensor.lavatrice')|trim}} | {{states(state_attr('sensor.energy_kwh_lavatrice', 'source')) | int(0) ~ ' W' if is_state('binary_sensor.lavatrice', 'on')}} | | <b>Ieri |{{ (state_attr('sensor.energy_day_lavatrice', 'last_period') |float(0) * states('input_number.costo_energia_casa') | float(0)) | round(2,default=0) }} â‚¬ | {{state_attr('sensor.energy_day_lavatrice','last_period') |float(0) | round(2) }}KWh | {{ history(state_attr('sensor.time_day_lavatrice', 'last_period')) | trim}} | {{state_attr('sensor.cycles_day_lavatrice','last_period')}} | |{% for periodo, periodo_lower in {'Oggi': 'day', 'Mese': 'month', 'Anno': 'year'}.items() %} | <b>{{ periodo }} |{{ (states('sensor.energy_' ~ periodo_lower ~ '_lavatrice') | float(0) * states('input_number.costo_energia_casa') | float(0)) | round(2, default=0) }} â‚¬|{{ states('sensor.energy_' ~ periodo_lower ~ '_lavatrice') | float(0) | round(2) }} | {{ history(states('sensor.time_' ~ periodo_lower ~ '_lavatrice')) | trim }}| {{states('sensor.cycles_'~ periodo_lower ~'_lavatrice')}} | |{% endfor %} --- {% set settimanale = state_attr('sensor.storico_lavatrice','Settimanale') %} Settimanale - | Giorno | Costo | Consumo | Tempo | Cicli | | :----- | :---: | :-----: | :----: | :---: | |{% for giorno in ['Lunedi', 'Martedi', 'Mercoledi', 'Giovedi', 'Venerdi', 'Sabato', 'Domenica'] %} | <b>{{ giorno }} | {{ settimanale[giorno].costo }} | {{ settimanale[giorno].consumo }} | {{ settimanale[giorno].tempo }} | {{ settimanale[giorno].cicli }} |{% endfor %} --- {% set settimanale = state_attr('sensor.storico_lavatrice','Mensile') %} Mensile - | Giorno | Costo | Consumo | Tempo | Cicli | | :----- | :---: | :-----: | :----: | :---: | |{% for giorno in ['Gennaio', 'Febbraio', 'Marzo', 'Aprile', 'Maggio', 'Giugno', 'Luglio', 'Agosto', 'Settembre', 'Ottobre', 'Novembre', 'Dicembre'] %} | <b>{{ giorno }} | {{ settimanale[giorno].costo }} | {{ settimanale[giorno].consumo }} | {{ settimanale[giorno].tempo }} | {{ settimanale[giorno].cicli }} |{% endfor %} --- Ultimo reset statistiche il {{as_local(state_attr('script.reset_sensori_lavatrice', 'last_triggered')).strftime('%d/%m/%Y %H:%M') }}) renders=26>
Error while processing template: Template<template=({% from 'history_stats_custom.jinja' import last_use, history %} Generale - {% set fine = state_attr('sensor.lavaggio_terminato','time') | timestamp_custom('%d/%m/%Y alle %H:%M') %} {% if is_state('input_boolean.check_ritirare_panni', 'on') %} {{ '### Panni da ritirare dal ' + fine }} {%elif is_state('binary_sensor.lavatrice', 'on') %} {{ '### Lavatrice in funzione' }} {%else%} {{ 'Ultimo lavaggio terminato il ' + fine }} {% endif %} | Periodo | Costo (â‚¬) | Consumo (KWh) | Tempo | Cicli |:--------|:----------:|:-------------:|:-----:|:--: | <b>Ultimo|{{ ((states[state_attr('sensor.energy_day_lavatrice', 'source')].state | float(0) - state_attr('sensor.lavaggio_iniziato','consumo_iniziale')|float(0)) * (states('input_number.costo_energia_casa') | float(0))) | round(2, default=0)}} â‚¬ | {{ (states[state_attr('sensor.energy_day_lavatrice', 'source')].state | float(0) - state_attr('sensor.lavaggio_iniziato', 'consumo_iniziale') |float(0)) | round(2)}} kWh | {{last_use('sensor.lavaggio_iniziato','sensor.lavaggio_terminato','binary_sensor.lavatrice')|trim}} | {{states(state_attr('sensor.energy_kwh_lavatrice', 'source')) | int(0) ~ ' W' if is_state('binary_sensor.lavatrice', 'on')}} | | <b>Ieri |{{ (state_attr('sensor.energy_day_lavatrice', 'last_period') |float(0) * states('input_number.costo_energia_casa') | float(0)) | round(2,default=0) }} â‚¬ | {{state_attr('sensor.energy_day_lavatrice','last_period') |float(0) | round(2) }}KWh | {{ history(state_attr('sensor.time_day_lavatrice', 'last_period')) | trim}} | {{state_attr('sensor.cycles_day_lavatrice','last_period')}} | |{% for periodo, periodo_lower in {'Oggi': 'day', 'Mese': 'month', 'Anno': 'year'}.items() %} | <b>{{ periodo }} |{{ (states('sensor.energy_' ~ periodo_lower ~ '_lavatrice') | float(0) * states('input_number.costo_energia_casa') | float(0)) | round(2, default=0) }} â‚¬|{{ states('sensor.energy_' ~ periodo_lower ~ '_lavatrice') | float(0) | round(2) }} | {{ history(states('sensor.time_' ~ periodo_lower ~ '_lavatrice')) | trim }}| {{states('sensor.cycles_'~ periodo_lower ~'_lavatrice')}} | |{% endfor %} --- {% set settimanale = state_attr('sensor.storico_lavatrice','Settimanale') %} Settimanale - | Giorno | Costo | Consumo | Tempo | Cicli | | :----- | :---: | :-----: | :----: | :---: | |{% for giorno in ['Lunedi', 'Martedi', 'Mercoledi', 'Giovedi', 'Venerdi', 'Sabato', 'Domenica'] %} | <b>{{ giorno }} | {{ settimanale[giorno].costo }} | {{ settimanale[giorno].consumo }} | {{ settimanale[giorno].tempo }} | {{ settimanale[giorno].cicli }} |{% endfor %} --- {% set settimanale = state_attr('sensor.storico_lavatrice','Mensile') %} Mensile - | Giorno | Costo | Consumo | Tempo | Cicli | | :----- | :---: | :-----: | :----: | :---: | |{% for giorno in ['Gennaio', 'Febbraio', 'Marzo', 'Aprile', 'Maggio', 'Giugno', 'Luglio', 'Agosto', 'Settembre', 'Ottobre', 'Novembre', 'Dicembre'] %} | <b>{{ giorno }} | {{ settimanale[giorno].costo }} | {{ settimanale[giorno].consumo }} | {{ settimanale[giorno].tempo }} | {{ settimanale[giorno].cicli }} |{% endfor %} --- Ultimo reset statistiche il {{as_local(state_attr('script.reset_sensori_lavatrice', 'last_triggered')).strftime('%d/%m/%Y %H:%M') }}) renders=30>
Error while processing template: Template<template=({% from 'history_stats_custom.jinja' import last_use, history %} Generale - {% set fine = state_attr('sensor.lavaggio_terminato','time') | timestamp_custom('%d/%m/%Y alle %H:%M') %} {% if is_state('input_boolean.check_ritirare_panni', 'on') %} {{ '### Panni da ritirare dal ' + fine }} {%elif is_state('binary_sensor.lavatrice', 'on') %} {{ '### Lavatrice in funzione' }} {%else%} {{ 'Ultimo lavaggio terminato il ' + fine }} {% endif %} | Periodo | Costo (â‚¬) | Consumo (KWh) | Tempo | Cicli |:--------|:----------:|:-------------:|:-----:|:--: | <b>Ultimo|{{ ((states[state_attr('sensor.energy_day_lavatrice', 'source')].state | float(0) - state_attr('sensor.lavaggio_iniziato','consumo_iniziale')|float(0)) * (states('input_number.costo_energia_casa') | float(0))) | round(2, default=0)}} â‚¬ | {{ (states[state_attr('sensor.energy_day_lavatrice', 'source')].state | float(0) - state_attr('sensor.lavaggio_iniziato', 'consumo_iniziale') |float(0)) | round(2)}} kWh | {{last_use('sensor.lavaggio_iniziato','sensor.lavaggio_terminato','binary_sensor.lavatrice')|trim}} | {{states(state_attr('sensor.energy_kwh_lavatrice', 'source')) | int(0) ~ ' W' if is_state('binary_sensor.lavatrice', 'on')}} | | <b>Ieri |{{ (state_attr('sensor.energy_day_lavatrice', 'last_period') |float(0) * states('input_number.costo_energia_casa') | float(0)) | round(2,default=0) }} â‚¬ | {{state_attr('sensor.energy_day_lavatrice','last_period') |float(0) | round(2) }}KWh | {{ history(state_attr('sensor.time_day_lavatrice', 'last_period')) | trim}} | {{state_attr('sensor.cycles_day_lavatrice','last_period')}} | |{% for periodo, periodo_lower in {'Oggi': 'day', 'Mese': 'month', 'Anno': 'year'}.items() %} | <b>{{ periodo }} |{{ (states('sensor.energy_' ~ periodo_lower ~ '_lavatrice') | float(0) * states('input_number.costo_energia_casa') | float(0)) | round(2, default=0) }} â‚¬|{{ states('sensor.energy_' ~ periodo_lower ~ '_lavatrice') | float(0) | round(2) }} | {{ history(states('sensor.time_' ~ periodo_lower ~ '_lavatrice')) | trim }}| {{states('sensor.cycles_'~ periodo_lower ~'_lavatrice')}} | |{% endfor %} --- {% set settimanale = state_attr('sensor.storico_lavatrice','Settimanale') %} Settimanale - | Giorno | Costo | Consumo | Tempo | Cicli | | :----- | :---: | :-----: | :----: | :---: | |{% for giorno in ['Lunedi', 'Martedi', 'Mercoledi', 'Giovedi', 'Venerdi', 'Sabato', 'Domenica'] %} | <b>{{ giorno }} | {{ settimanale[giorno].costo }} | {{ settimanale[giorno].consumo }} | {{ settimanale[giorno].tempo }} | {{ settimanale[giorno].cicli }} |{% endfor %} --- {% set settimanale = state_attr('sensor.storico_lavatrice','Mensile') %} Mensile - | Giorno | Costo | Consumo | Tempo | Cicli | | :----- | :---: | :-----: | :----: | :---: | |{% for giorno in ['Gennaio', 'Febbraio', 'Marzo', 'Aprile', 'Maggio', 'Giugno', 'Luglio', 'Agosto', 'Settembre', 'Ottobre', 'Novembre', 'Dicembre'] %} | <b>{{ giorno }} | {{ settimanale[giorno].costo }} | {{ settimanale[giorno].consumo }} | {{ settimanale[giorno].tempo }} | {{ settimanale[giorno].cicli }} |{% endfor %} --- Ultimo reset statistiche il {{as_local(state_attr('script.reset_sensori_lavatrice', 'last_triggered')).strftime('%d/%m/%Y %H:%M') }}) renders=34>
Error while processing template: Template<template=({% from 'history_stats_custom.jinja' import last_use, history %} Generale - {% set fine = state_attr('sensor.lavaggio_terminato','time') | timestamp_custom('%d/%m/%Y alle %H:%M') %} {% if is_state('input_boolean.check_ritirare_panni', 'on') %} {{ '### Panni da ritirare dal ' + fine }} {%elif is_state('binary_sensor.lavatrice', 'on') %} {{ '### Lavatrice in funzione' }} {%else%} {{ 'Ultimo lavaggio terminato il ' + fine }} {% endif %} | Periodo | Costo (â‚¬) | Consumo (KWh) | Tempo | Cicli |:--------|:----------:|:-------------:|:-----:|:--: | <b>Ultimo|{{ ((states[state_attr('sensor.energy_day_lavatrice', 'source')].state | float(0) - state_attr('sensor.lavaggio_iniziato','consumo_iniziale')|float(0)) * (states('input_number.costo_energia_casa') | float(0))) | round(2, default=0)}} â‚¬ | {{ (states[state_attr('sensor.energy_day_lavatrice', 'source')].state | float(0) - state_attr('sensor.lavaggio_iniziato', 'consumo_iniziale') |float(0)) | round(2)}} kWh | {{last_use('sensor.lavaggio_iniziato','sensor.lavaggio_terminato','binary_sensor.lavatrice')|trim}} | {{states(state_attr('sensor.energy_kwh_lavatrice', 'source')) | int(0) ~ ' W' if is_state('binary_sensor.lavatrice', 'on')}} | | <b>Ieri |{{ (state_attr('sensor.energy_day_lavatrice', 'last_period') |float(0) * states('input_number.costo_energia_casa') | float(0)) | round(2,default=0) }} â‚¬ | {{state_attr('sensor.energy_day_lavatrice','last_period') |float(0) | round(2) }}KWh | {{ history(state_attr('sensor.time_day_lavatrice', 'last_period')) | trim}} | {{state_attr('sensor.cycles_day_lavatrice','last_period')}} | |{% for periodo, periodo_lower in {'Oggi': 'day', 'Mese': 'month', 'Anno': 'year'}.items() %} | <b>{{ periodo }} |{{ (states('sensor.energy_' ~ periodo_lower ~ '_lavatrice') | float(0) * states('input_number.costo_energia_casa') | float(0)) | round(2, default=0) }} â‚¬|{{ states('sensor.energy_' ~ periodo_lower ~ '_lavatrice') | float(0) | round(2) }} | {{ history(states('sensor.time_' ~ periodo_lower ~ '_lavatrice')) | trim }}| {{states('sensor.cycles_'~ periodo_lower ~'_lavatrice')}} | |{% endfor %} --- {% set settimanale = state_attr('sensor.storico_lavatrice','Settimanale') %} Settimanale - | Giorno | Costo | Consumo | Tempo | Cicli | | :----- | :---: | :-----: | :----: | :---: | |{% for giorno in ['Lunedi', 'Martedi', 'Mercoledi', 'Giovedi', 'Venerdi', 'Sabato', 'Domenica'] %} | <b>{{ giorno }} | {{ settimanale[giorno].costo }} | {{ settimanale[giorno].consumo }} | {{ settimanale[giorno].tempo }} | {{ settimanale[giorno].cicli }} |{% endfor %} --- {% set settimanale = state_attr('sensor.storico_lavatrice','Mensile') %} Mensile - | Giorno | Costo | Consumo | Tempo | Cicli | | :----- | :---: | :-----: | :----: | :---: | |{% for giorno in ['Gennaio', 'Febbraio', 'Marzo', 'Aprile', 'Maggio', 'Giugno', 'Luglio', 'Agosto', 'Settembre', 'Ottobre', 'Novembre', 'Dicembre'] %} | <b>{{ giorno }} | {{ settimanale[giorno].costo }} | {{ settimanale[giorno].consumo }} | {{ settimanale[giorno].tempo }} | {{ settimanale[giorno].cicli }} |{% endfor %} --- Ultimo reset statistiche il {{as_local(state_attr('script.reset_sensori_lavatrice', 'last_triggered')).strftime('%d/%m/%Y %H:%M') }}) renders=38>
Error while processing template: Template<template=({% from 'history_stats_custom.jinja' import last_use, history %} Generale - {% set fine = state_attr('sensor.lavaggio_terminato','time') | timestamp_custom('%d/%m/%Y alle %H:%M') %} {% if is_state('input_boolean.check_ritirare_panni', 'on') %} {{ '### Panni da ritirare dal ' + fine }} {%elif is_state('binary_sensor.lavatrice', 'on') %} {{ '### Lavatrice in funzione' }} {%else%} {{ 'Ultimo lavaggio terminato il ' + fine }} {% endif %} | Periodo | Costo (â‚¬) | Consumo (KWh) | Tempo | Cicli |:--------|:----------:|:-------------:|:-----:|:--: | <b>Ultimo|{{ ((states[state_attr('sensor.energy_day_lavatrice', 'source')].state | float(0) - state_attr('sensor.lavaggio_iniziato','consumo_iniziale')|float(0)) * (states('input_number.costo_energia_casa') | float(0))) | round(2, default=0)}} â‚¬ | {{ (states[state_attr('sensor.energy_day_lavatrice', 'source')].state | float(0) - state_attr('sensor.lavaggio_iniziato', 'consumo_iniziale') |float(0)) | round(2)}} kWh | {{last_use('sensor.lavaggio_iniziato','sensor.lavaggio_terminato','binary_sensor.lavatrice')|trim}} | {{states(state_attr('sensor.energy_kwh_lavatrice', 'source')) | int(0) ~ ' W' if is_state('binary_sensor.lavatrice', 'on')}} | | <b>Ieri |{{ (state_attr('sensor.energy_day_lavatrice', 'last_period') |float(0) * states('input_number.costo_energia_casa') | float(0)) | round(2,default=0) }} â‚¬ | {{state_attr('sensor.energy_day_lavatrice','last_period') |float(0) | round(2) }}KWh | {{ history(state_attr('sensor.time_day_lavatrice', 'last_period')) | trim}} | {{state_attr('sensor.cycles_day_lavatrice','last_period')}} | |{% for periodo, periodo_lower in {'Oggi': 'day', 'Mese': 'month', 'Anno': 'year'}.items() %} | <b>{{ periodo }} |{{ (states('sensor.energy_' ~ periodo_lower ~ '_lavatrice') | float(0) * states('input_number.costo_energia_casa') | float(0)) | round(2, default=0) }} â‚¬|{{ states('sensor.energy_' ~ periodo_lower ~ '_lavatrice') | float(0) | round(2) }} | {{ history(states('sensor.time_' ~ periodo_lower ~ '_lavatrice')) | trim }}| {{states('sensor.cycles_'~ periodo_lower ~'_lavatrice')}} | |{% endfor %} --- {% set settimanale = state_attr('sensor.storico_lavatrice','Settimanale') %} Settimanale - | Giorno | Costo | Consumo | Tempo | Cicli | | :----- | :---: | :-----: | :----: | :---: | |{% for giorno in ['Lunedi', 'Martedi', 'Mercoledi', 'Giovedi', 'Venerdi', 'Sabato', 'Domenica'] %} | <b>{{ giorno }} | {{ settimanale[giorno].costo }} | {{ settimanale[giorno].consumo }} | {{ settimanale[giorno].tempo }} | {{ settimanale[giorno].cicli }} |{% endfor %} --- {% set settimanale = state_attr('sensor.storico_lavatrice','Mensile') %} Mensile - | Giorno | Costo | Consumo | Tempo | Cicli | | :----- | :---: | :-----: | :----: | :---: | |{% for giorno in ['Gennaio', 'Febbraio', 'Marzo', 'Aprile', 'Maggio', 'Giugno', 'Luglio', 'Agosto', 'Settembre', 'Ottobre', 'Novembre', 'Dicembre'] %} | <b>{{ giorno }} | {{ settimanale[giorno].costo }} | {{ settimanale[giorno].consumo }} | {{ settimanale[giorno].tempo }} | {{ settimanale[giorno].cicli }} |{% endfor %} --- Ultimo reset statistiche il {{as_local(state_attr('script.reset_sensori_lavatrice', 'last_triggered')).strftime('%d/%m/%Y %H:%M') }}) renders=42>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 604, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2639, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.12/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/local/lib/python3.12/site-packages/jinja2/sandbox.py", line 394, in call
    return __context.call(__obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/dt.py", line 159, in as_local
    if dattim.tzinfo == DEFAULT_TIME_ZONE:
       ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'tzinfo'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 716, in async_render_to_info
    render_info._result = self.async_render(  # noqa: SLF001
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 606, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: AttributeError: 'NoneType' object has no attribute 'tzinfo'

**Comment by Redrex85** [comment]
problema risolto, mettendo il nuovo aggiornamento e la nuova card
